[package]
name = "definitely_safe_notebook_since_i_have_forbid_unsafe_code"
version = "0.1.0"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallvec = "=1.6.0"